title: "Gracias, Chema"
description: "Sitio digital en recuerdo de José María “Chema” Tojeira — un espacio de gratitud y memoria colectiva."
lang: es

# Remove baseurl since you're now using a custom domain
# baseurl: "/graciaschema-site"

# Optional: set the full site URL
url: "https://www.graciaschema.org"

# Markdown engine + allow block HTML
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
plugins:
  - jekyll-sitemap
