title: "Gracias, Chema"
description: "Memorial digital para José María “Chema” Tojeira. Historias personales, recuerdos y gratitud."
lang: es

remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme

baseurl: "/graciaschema-site"   # keep this until you connect graciaschema.org
