title: "Gracias, Chema"
description: "Memorial digital para José María “Chema” Tojeira. Historias personales, recuerdos y gratitud."
lang: es

remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme

# While the site lives at https://albertovth.github.io/graciaschema-site
baseurl: "/graciaschema-site"

# Markdown engine + allow block HTML
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true

