title: "Gracias, Chema"
description: "Memorial digital para José María “Chema” Tojeira. Historias personales, recuerdos y gratitud."
lang: es

# Use an official GitHub Pages theme via remote_theme
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
