title: "Gracias, Chema"
description: "Memorial digital para José María “Chema” Tojeira. Historias personales, recuerdos y gratitud."
lang: es

# REMOVE remote_theme and its plugin
# remote_theme: pages-themes/merlot@v0.2.0

# No plugins necessary if you're not using remote_theme
# plugins:
#   - jekyll-remote-theme

# Site base path
baseurl: "/graciaschema-site"

# Markdown engine + allow block HTML
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
