title: "Gracias, Chema"
description: "Memorial digital para José María “Chema” Tojeira. Historias personales, recuerdos y gratitud."
lang: es

remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme

# Keep this while the site lives under https://albertovth.github.io/graciaschema-site
baseurl: "/graciaschema-site"

# Optional, makes sure markdown is parsed with Kramdown
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
